name: DEV - Tutorial Backend Deploy
on:
  repository_dispatch:
    types: [bokie-tutorial-backend-cd-dev]
  workflow_dispatch:


env:
  REPOSITORY: "tarathep/bokie-tutorial-backend"
  APP_NAME: bokie-tutorial-backend
  AZURE_WEB_APP_NAME: app-bokie-tutorial-backend-dev-001
  CONTAINER_REPOSITORY: "acrbokietutorial001.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"

jobs:
  build-and-deploy-app-service:
    name: Build and Deploy
    #runs-on: [self-hosted, example-dev]
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: "Checkout pipelines"
      uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: 'Set subscription'
      run: az account set --subscription 1d00f364-f62c-4896-a77d-e24d36e7d9c8
    
    - name: "Deploy to Azure WebApp"
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        images: '${{ env.CONTAINER_REPOSITORY }}/${{ env.APP_NAME }}:${{env.IMAGE_TAG}}'

    - name: Set Web App Settings
      uses: Azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        app-settings-json: |
          [
            {
              "name": "MONGODB_CONNECTION_STRING",
              "value": "mongodb://cosmos-bokie-tutorial-001:hR3VcDZEwWwdDR4YmHjO86HsciGZp82TMeBIF2dPCJ9WSqRWZ4iWT9lEIW3m0HHZkIu5BrTPa5uu4DnJIoaBKQ==@cosmos-bokie-tutorial-001.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@cosmos-bokie-tutorial-001@",
              "slotSetting": false
            },
            {
              "name": "PORT",
              "value": "80",
              "slotSetting": false
            }
          ]