name: DEV - Tutorial Frontend Deploy
on:
  repository_dispatch:
    types: [bokie-tutorial-frontend-cd-dev]
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        default: "dev"
      ref:
        description: "Repository branch or tag"
        required: true
        default: "develop"

env:
  REPOSITORY: "tarathep/bokie-tutorial-frontend"
  APP_NAME: bokie-tutorial-frontend
  CONTAINER_REPOSITORY: "acrbokietutorial001.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"
  GITREF: ${{ github.event_name == 'repository_dispatch' && 'develop' || github.event.inputs.ref }}

  


jobs:
  build-and-deploy-app-service:
    name: Build and Deploy
    #runs-on: [self-hosted, example-dev]
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'repository_dispatch' && 'dev' || github.event.inputs.env }}
    steps:
    - name: "Checkout pipelines"
      uses: actions/checkout@v2
      with:
        path: .pipeline

    - name: "Checkout project"
      uses: actions/checkout@v2
      with:
        repository: ${{ env.REPOSITORY }}
        ref: ${{ env.GITREF }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: "List working directory"
      run: ls
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: 'Set subscription'
      run: az account set --subscription 1d00f364-f62c-4896-a77d-e24d36e7d9c8
    
    - name: "Deploy to Azure WebApp"
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ format('app-bokie-tutorial-frontend-{0}-001', 'dev') }}
        images: '${{ env.CONTAINER_REPOSITORY }}/${{ env.APP_NAME }}:${{env.IMAGE_TAG}}'

    - name: Set Web App Settings
      uses: Azure/appservice-settings@v1
      with:
        app-name: ${{ format('app-bokie-tutorial-frontend-{0}-001', 'dev') }}
        app-settings-json: |
          [
            {
              "name": "VUE_APP_ENPOINT_API_BACKEND",
              "value": "https://app-bokie-tutorial-backend-dev-001.azurewebsites.net/api/tutorials",
              "slotSetting": false
            }
          ]