name: SIT - Tutorial Backend Deploy
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Image Tag"
        required: true
        default: "0.0.1"

env:
  REPOSITORY: "tarathep/bokie-tutorial-backend"
  APP_NAME: bokie-tutorial-backend
  AZURE_WEB_APP_NAME: app-bokie-tutorial-backend-sit-001
  CONTAINER_REPOSITORY: "acrbokietutorial001.azurecr.io"
  IMAGE_TAG: ${{ github.event.inputs.ref }}  


jobs:
  deploy-app-service:
    name: Build and Deploy
    #runs-on: [self-hosted, example-dev]
    runs-on: ubuntu-latest
    environment: sit
    steps:
    - name: "Checkout pipelines"
      uses: actions/checkout@v2
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: 'Set subscription'
      run: az account set --subscription 1d00f364-f62c-4896-a77d-e24d36e7d9c8
    
    - name: "Deploy to Azure WebApp"
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        images: '${{ env.CONTAINER_REPOSITORY }}/${{ env.APP_NAME }}:${{env.IMAGE_TAG}}'

    - name: Set Web App Settings
      uses: Azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEB_APP_NAME }}
        app-settings-json: |
          [
            {
              "name": "VUE_APP_ENPOINT_API_BACKEND",
              "value": "https://app-bokie-tutorial-backend-dev-001.azurewebsites.net/api/tutorials",
              "slotSetting": false
            }
          ]